import { categoryByKey, deductibleCents, EXPENSE_CATEGORIES, sumCents } from "@toreroflow/core";

export interface ExportableExpense {
  name: string;
  categoryLine: string;
  amountCents: number | null;
}

export interface ScheduleCGroup {
  key: string;
  scheduleCLine: string;
  label: string;
  totalCents: number;
  /** What may actually be claimed. Differs from the total for meals only. */
  deductibleCents: number;
  items: Array<{ name: string; amountCents: number }>;
}

/**
 * Groups a year's expenses by their Schedule C line.
 *
 * Unentered bills are excluded rather than counted as zero, because a total
 * that quietly includes an unknown is worse on a tax document than one that
 * is visibly short. Empty categories are omitted so the export lists only
 * lines with something on them.
 */
export function groupForScheduleC(expenses: ExportableExpense[]): ScheduleCGroup[] {
  const groups: ScheduleCGroup[] = [];

  for (const category of EXPENSE_CATEGORIES) {
    const mine = expenses.filter(
      (e) => e.categoryLine === category.key && e.amountCents !== null,
    );
    if (mine.length === 0) continue;

    const totalCents = sumCents(mine.map((e) => e.amountCents));
    groups.push({
      key: category.key,
      scheduleCLine: category.scheduleCLine,
      label: category.label,
      totalCents,
      deductibleCents: deductibleCents(category.key, totalCents),
      items: mine.map((e) => ({ name: e.name, amountCents: e.amountCents! })),
    });
  }

  return groups;
}

/** Kept exported so a caller can label an unknown key without importing core. */
export function labelFor(key: string): string {
  return categoryByKey(key)?.label ?? key;
}

export interface TaxExportData {
  year: number;
  business: {
    legalName: string;
    ein: string | null;
    businessCode: string | null;
    accountingMethod: string;
  };
  grossReceiptsCents: number;
  receiptsByClient: Array<{ name: string; cents: number }>;
  groups: ScheduleCGroup[];
}

function esc(text: string): string {
  return text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function money(cents: number): string {
  return (cents / 100).toLocaleString("en-US", { style: "currency", currency: "USD" });
}

/**
 * The year-end document.
 *
 * Every expense sits under its Schedule C line so a CPA reads the form's own
 * structure rather than translating ours. Where a line's deductible figure
 * differs from what was spent, both are shown and labelled, because a single
 * halved number with no explanation looks like an arithmetic error.
 */
export function buildTaxExportHtml(data: TaxExportData): string {
  const receipts = data.receiptsByClient
    .map((r) => `<tr><td>${esc(r.name)}</td><td class="r">${money(r.cents)}</td></tr>`)
    .join("");

  const groups = data.groups
    .map((g) => {
      const items = g.items
        .map((i) => `<tr><td>${esc(i.name)}</td><td class="r">${money(i.amountCents)}</td></tr>`)
        .join("");
      const split =
        g.deductibleCents !== g.totalCents
          ? `<tr class="tot"><td>Deductible at 50%</td><td class="r">${money(g.deductibleCents)}</td></tr>`
          : "";
      return `<h3>Line ${esc(g.scheduleCLine)} &middot; ${esc(g.label)}</h3>
        <table>${items}
          <tr class="tot"><td>Spent</td><td class="r">${money(g.totalCents)}</td></tr>
          ${split}
        </table>`;
    })
    .join("");

  const totalDeductible = data.groups.reduce((n, g) => n + g.deductibleCents, 0);

  return `<!doctype html><meta charset="utf-8"><title>Schedule C ${data.year}</title>
<style>
  body{font-family:-apple-system,"Segoe UI",system-ui,sans-serif;color:#111;margin:0;padding:48px 56px}
  h1{font-size:26px;margin:0 0 6px}
  h3{font-size:14px;margin:26px 0 0}
  .muted{color:#777;font-size:13px;line-height:1.7}
  table{width:100%;border-collapse:collapse;font-size:13px;margin-top:8px}
  td{padding:7px 0;border-bottom:1px solid #ececec}
  td.r{text-align:right}
  tr.tot td{font-weight:700;border-bottom:2px solid #111}
  .grand{margin-top:30px;padding-top:14px;border-top:2px solid #111;font-size:16px;font-weight:700;
    display:flex;justify-content:space-between}
  .foot{margin-top:36px;font-size:11px;color:#888;line-height:1.7}
</style>
<h1>Schedule C summary, ${data.year}</h1>
<div class="muted">
  ${esc(data.business.legalName)}<br>
  ${data.business.ein ? `EIN ${esc(data.business.ein)}<br>` : "EIN not recorded<br>"}
  ${data.business.businessCode ? `Business code ${esc(data.business.businessCode)}<br>` : "Business code not recorded<br>"}
  Accounting method: ${esc(data.business.accountingMethod)}
</div>

<h3>Gross receipts</h3>
<table>${receipts}
  <tr class="tot"><td>Total</td><td class="r">${money(data.grossReceiptsCents)}</td></tr>
</table>

${groups}

<div class="grand"><span>Total deductible expenses</span><span>${money(totalDeductible)}</span></div>

<div class="foot">
  Generated by Toreroflow on ${new Date().toLocaleDateString("en-US")}. These figures are records
  kept in Toreroflow and are not tax advice. Business meals are reported at the 50% deductible
  rate for 2026. Expenses with no amount recorded are excluded entirely rather than counted as
  zero, so confirm every bill has been entered before filing.
</div>`;
}
